import type { Metadata } from "next"

import Footer from "@/components/global/footer/Footer"
import Header from "@/components/global/header/Header"
import Theme from "@/components/global/theme/Theme"
import FontsProvider from "@/lib/providers/FontsProvider"
import ReactQueryProvider from "@/lib/providers/ReactQueryProvider"
import "@/styles/globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <FontsProvider>
          <Theme>
            <ReactQueryProvider>
              <Header />
              {children}
              <Footer />
            </ReactQueryProvider>
          </Theme>
        </FontsProvider>
      </body>
    </html>
  )
}
