import type { Metadata } from "next"
import localFont from "next/font/local"

import Footer from "@/components/global/footer/Footer"
import GridHelper from "@/components/global/gridHelper/GridHelper"
import Header from "@/components/global/header/Header"
import Theme from "@/components/global/theme/Theme"
import ReactQueryProvider from "@/lib/providers/ReactQueryProvider"
import "@/styles/globals.css"

const GTFlexa = localFont({
  src: [
    {
      path: "../fonts/GT-Flexa-Expanded-Regular.woff2",
      weight: "400",
    },
    {
      path: "../fonts/GT-Flexa-Expanded-Medium.woff2",
      weight: "500",
    },
  ],
  variable: "--font-headline",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${GTFlexa.variable} antialiased`}>
        {process.env.NEXT_PUBLIC_ENVIRONMENT === "development" && <GridHelper />}
        <Theme>
          <ReactQueryProvider>
            <Header />
            <div className="bg-background">{children}</div>
            <Footer />
          </ReactQueryProvider>
        </Theme>
      </body>
    </html>
  )
}
