import type { Metadata } from "next"
import localFont from "next/font/local"

import Footer from "@/components/global/footer/Footer"
import GridHelper from "@/components/global/gridHelper/GridHelper"
import Header from "@/components/global/header/Header"
import Theme from "@/components/global/theme/Theme"
import ReactQueryProvider from "@/lib/providers/ReactQueryProvider"
import "@/styles/globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

// When adding or changing fonts, remember to update the imports in .storybook/preview.tsx
const GTFlexa = localFont({
  src: [
    {
      path: "../public/fonts/GT-Flexa-Expanded-Regular.woff2",
      weight: "400",
    },
    {
      path: "../public/fonts/GT-Flexa-Expanded-Medium.woff2",
      weight: "500",
    },
  ],
  variable: "--font-headline",
  display: "swap",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${GTFlexa.variable} antialiased`}>
        <GridHelper hideInProduction />
        <Theme>
          <ReactQueryProvider>
            <Header />
            <div className="flex h-full min-h-screen-minus-navigation-height w-full flex-col">
              {children}
            </div>
            <Footer />
          </ReactQueryProvider>
        </Theme>
      </body>
    </html>
  )
}
