const app = {
  "app.url": () => {
    if (process.env.NEXT_PUBLIC_APP_URL) {
      return process.env.NEXT_PUBLIC_APP_URL
    }
    if (process.env.LAGOON_AUTOGENERATED_ROUTES) {
      const routes = process.env.LAGOON_AUTOGENERATED_ROUTES.split(",")
      for (const route of routes) {
        if (route.includes("node")) {
          return route
        }
      }
    }
    throw new Error("No app URL found.")
  },
}

export default app
