// TODO: This a momentary solution, we need to find a better way to handle this.
// TODO: And write a test for it plz.
const getConfig = (key: string) => {
  switch (key) {
    case "url.app":
      if (process.env.LAGOON_AUTOGENERATED_ROUTES) {
        const routes = process.env.LAGOON_AUTOGENERATED_ROUTES.split(",")
        for (const route of routes) {
          if (route.includes("node")) {
            return route
          }
        }
      }

      if (process.env.NEXT_PUBLIC_APP_URL) {
        return process.env.NEXT_PUBLIC_APP_URL
      }
  }
}

export default getConfig
