import { expect, test, vi } from "vitest"

import getConfig from "@/lib/config/config"
import MissingConfigurationError from "@/lib/config/errors/MissingConfigurationError"

test("That we can get the app url from Lagoon if NEXT_PUBLIC_APP_URL has not been defined already", async () => {
  vi.stubEnv(
    "LAGOON_AUTOGENERATED_ROUTES",
    "https://nginx.acme.com,https://node.acme.com,https://varnish.acme.com"
  )
  vi.stubEnv("NEXT_PUBLIC_APP_URL", undefined)

  const appUrl = getConfig("app.url")
  expect(appUrl).toBe("https://node.acme.com")
})

test("That an error is thrown if we ask for unknown config", async () => {
  expect(() => getConfig("unknown.thingy")).toThrowError(MissingConfigurationError)
})

test("That the env variable NEXT_PUBLIC_APP_URL has precedence over LAGOON_AUTOGENERATED_ROUTES", async () => {
  vi.stubEnv(
    "LAGOON_AUTOGENERATED_ROUTES",
    "https://nginx.acme.com,https://node.acme.com,https://varnish.acme.com"
  )
  vi.stubEnv("NEXT_PUBLIC_APP_URL", "https://hellboy.the-movie.com")

  const appUrl = getConfig("app.url")
  expect(appUrl).toBe("https://hellboy.the-movie.com")
})
