import { expect, test, vi } from "vitest"

import goConfig from "@/lib/config/config"
import MissingConfigurationError from "@/lib/config/errors/MissingConfigurationError"

test("That an error is thrown if we ask for unknown config", async () => {
  expect(() => goConfig("unknown.thingy")).toThrowError(MissingConfigurationError)
})

test("That the env variable NEXT_PUBLIC_APP_URL has precedence over LAGOON_AUTOGENERATED_ROUTES", async () => {
  const appUrl = goConfig("app.url")
  expect(appUrl).toBe("https://hellboy.the-movie.com")
})
