import { expect, test, vi } from "vitest"

import getConfig from "@/lib/config/config"

test.only("That we can get the app url from config", async () => {
  vi.stubEnv(
    "LAGOON_AUTOGENERATED_ROUTES",
    "https://nginx.acme.com,https://node.acme.com,https://varnish.acme.com"
  )
  const appUrl = getConfig("url.app")
  expect(appUrl).toBe("https://node.acme.com")
})

test("That we get undefined if we ask for unknown config", async () => {
  const appUrl = getConfig("url.unknown")

  expect(appUrl).toBeUndefined()
})
