import { describe } from "node:test"
import { expect, test } from "vitest"

import { getDplCmsGraphqlEndpoint } from "@/lib/helpers/dpl-cms.graphql"

describe("Dpl CMS graphql test suite", () => {
  test("That we can resolve the Dpl CMS endpoint graphql URL if the Lagoon Autogenerated Routes are set", async () => {
    const url = getDplCmsGraphqlEndpoint()
    expect(url).toBe("https://varnish.acme.com/graphql")
  })
})
