name: Next.js E2E Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  check:
    name: E2E job with Cypress
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0 # Required to retrieve git history

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: yarn install --frozen-lockfile --no-progress --non-interactive

      - name: Load environment variables
        uses: cardinalby/export-env-action@v2
        with:
          envFile: ".env.test"

      - name: Build the Nextjs app and run Cypress tests
        uses: cypress-io/github-action@v6
        env:
          # A bug in the current version of Nextjs causes NODE_ENV=test to brick the build
          # By overridding the variables here we can ensure that the correct urls are set
          TEST_MODE: true
          NEXT_PUBLIC_DPL_CMS_HOSTNAME: http://localhost:9000
          NEXT_PUBLIC_DPL_CMS_GRAPHQL_URL: http://localhost:9000/graphql
          NEXT_PUBLIC_GRAPHQL_SCHEMA_ENDPOINT_FBS: http://localhost:9000/graphql
          UNILOGIN_CLIENT_ID: http://localhost:9000/client
          UNILOGIN_WELLKNOWN_URL: http://localhost:9000
          NEXT_PUBLIC_APP_URL: http://localhost:3000

        with:
          install: false
          build: yarn build
          start: yarn start
          command: yarn cypress:run
          browser: chrome
